name: Caching and Artifacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          # 1ère fois : pas de cache pour cette clef donc le crée, les fois d'après le load
          # github.com -> Actions -> Caches
      - name: Display Cache Output
        run: echo "${{ toJSON(steps.cache-dependencies.outputs) }}"
      - name: Install dependencies
        run: npm install
      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/',
              { headers: { Accept: 'text/plain' } }
            );
            console.log(res.data);