# .github/workflows/call-workflow-from-workflows.yml dans github-actions
name: Call Workflow from Workflows Repository

on:
  push:
    branches:
      - main

jobs:
  call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Trigger the workflow in workflows repo using API
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/Gh-Actions-tests/workflows/simple-workflow.yml/dispatches \
          -d '{"ref":"main", "inputs": {"message": "Hello from github-actions!"}}'
