# .github/workflows/call-workflow-from-workflows.yml dans github-actions
name: Call Workflow from Workflows Repository

on:
  push:
    branches:
      - main

jobs:
  call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Trigger the workflow in workflows repo
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: Gh-Actions-tests/workflows  # Nom du repository contenant le workflow
          workflow: simple-workflow.yml         # Fichier du workflow dans workflows
          ref: main                             # La branche où le workflow doit s'exécuter
          inputs:                               # Paramètres à passer au workflow appelé
            message: "Hello from github-actions!"  # Entrée message
          token: ${{ secrets.GITHUB_TOKEN }}    # Utilisation du token GitHub pour l'authentification
