name: Pull Request comment
on:
  pull_request_target:
    types: [opened]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    # permissions table: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    # {} == no permissions
    # read-all / write-all permissions for all scopes
    permissions:
      issues: read
    steps:
      - name: Comment on New PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issuer.number,
              body: 'Thanks for contributing !'
            })