name: Backup Previous Commit
on:
  workflow_run: 
    workflows: [Get Previous Commits SHAs]
    types: [completed]
    

jobs:
  backup-previous-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use previous commit SHA
        run: |
          echo "The SHA of the previous commit is: ${{ env.PREVIOUS_SHA }}"
      
      - name: Create backup directory
        run: |
          BACKUP_DIR=${{ github.workspace }}/tmp/backup
          echo "BACKUP_DIR=$BACKUP_DIR" >> $GITHUB_ENV
          mkdir $BACKUP_DIR

      - name: Backup previous commit
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.PREVIOUS_SHA }}
          path: ${{ env.BACKUP_DIR }}

      - name: Check backup
        run: |
          echo "Contents of workspace:"
          ls -la ${{ github.workspace }}
          echo "Contents of $BACKUP_DIR:"
          ls -la ${{ env.BACKUP_DIR }}  # Affiche le contenu du répertoire de sauvegarde pour vérifier le clonage
          # Si le dépôt est cloné directement dans $BACKUP_DIR, accède-y pour vérifier le commit
          cd ${{ env.BACKUP_DIR }}
          echo "Current pwd:"
          pwd
          echo "Backup commit SHA:"
          git rev-parse HEAD  # Affiche le SHA du commit pour confirmation
#      - name: Archive backup (optional)
#        run: |
#          cd /path/to/backup/directory
#          tar -czf backup-$(date +'%Y%m%d%H%M%S').tar.gz .
