name: Get Previous Commits SHAs
on:
  push:
    branches:
      - main

jobs:
  get-previous-shas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Count commits and get SHAs
        id: get_shas
        run: |
          # Compte le nombre de commits dans l'historique
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "Total number of commits: $COMMIT_COUNT"

          # Vérifie si il y a assez de commits
          if [ "$COMMIT_COUNT" -ge 4 ]; then
              PREVIOUS_SHA=$(git rev-parse HEAD~1)  # 1 commit précédent
              TWO_COMMITS_BEFORE_SHA=$(git rev-parse HEAD~2)  # 2 commits précédents
              THREE_COMMITS_BEFORE_SHA=$(git rev-parse HEAD~3)  # 3 commits précédents

              echo "Previous commit SHA: $PREVIOUS_SHA"
              echo "SHA of two commits before: $TWO_COMMITS_BEFORE_SHA"
              echo "SHA of three commits before: $THREE_COMMITS_BEFORE_SHA"

              # Stocker les SHAs dans des variables d'environnement
              echo "PREVIOUS_SHA=$PREVIOUS_SHA" >> $GITHUB_ENV
              echo "TWO_COMMITS_BEFORE_SHA=$TWO_COMMITS_BEFORE_SHA" >> $GITHUB_ENV
              echo "THREE_COMMITS_BEFORE_SHA=$THREE_COMMITS_BEFORE_SHA" >> $GITHUB_ENV
          else
              echo "Not enough commits available."
              exit 1  # Échoue le job si pas assez de commits
          fi
