name: Backup Previous Commit
on:
  # workflow_run: 
  #   workflows: [Get Previous Commits SHAs]
  #   types: [completed]
  push:
    paths:
      - "!app.js"

jobs:
  backup-previous-commit:
    runs-on: ubuntu-latest
    steps:
      - name: First check
        run: |
          echo "Contents of workspace before first checkout:"
          ls -la ${{ github.workspace }}
          PROJECT_DIR=${{ github.workspace }}/project
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Backup dir:"
          echo $PROJECT_DIR
          mkdir -p $PROJECT_DIR

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: ${{ env.PROJECT_DIR }}

      - name: Second check
        run: |
          echo "Contents of workspace after first checkout:"
          ls -la ${{ github.workspace }}
          echo "Contents of project dir:"
          ls -la ${{ env.PROJECT_DIR }}
          
      - name: Use previous commit SHA
        run: |
          echo "The SHA of the previous commit is:"
          echo ${{ env.PREVIOUS_SHA }}
      
      - name: Create backup directory
        run: |
          BACKUP_DIR=${{ github.workspace }}/backup
          echo "BACKUP_DIR=$BACKUP_DIR" >> $GITHUB_ENV
          echo "Backup dir:"
          echo $BACKUP_DIR
          mkdir -p $BACKUP_DIR

      - name: Backup previous commit
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.PREVIOUS_SHA }}
          path: ${{ env.BACKUP_DIR }}

      - name: Check backup
        run: |
          echo "Contents of workspace:"
          ls -la ${{ github.workspace }}
          # displays the files inside the backup directory to verify the clone
          echo "Contents of $BACKUP_DIR:"
          ls -la ${{ env.BACKUP_DIR }}
          # go inside the backup directory to verify the commit's SHA
          cd ${{ env.BACKUP_DIR }}
          echo "Current pwd:"
          pwd
          # displays the commit's SHA for confirmation
          echo "Backup commit SHA:"
          git rev-parse HEAD
#      - name: Archive backup (optional)
#        run: |
#          cd /path/to/backup/directory
#          tar -czf backup-$(date +'%Y%m%d%H%M%S').tar.gz .
