name: Backup Previous Commit
on:
  workflow_run: 
    workflows: [Get Previous Commits SHAs]
    types: [completed]
    

jobs:
  backup-previous-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use previous commit SHA
        run: |
          echo "The SHA of the previous commit is: ${{ env.PREVIOUS_SHA }}"
      
      - name: Create backup directory
        run: |
          BACKUP_DIR=/tmp/backup
          mkdir -p $BACKUP_DIR

      - name: Backup previous commit
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.PREVIOUS_SHA }}
          path: $BACKUP_DIR

      - name: Check backup
        run: |
          pwd $BACKUP_DIR
#      - name: Archive backup (optional)
#        run: |
#          cd /path/to/backup/directory
#          tar -czf backup-$(date +'%Y%m%d%H%M%S').tar.gz .
