name: Prototype v1
on: [workflow_dispatch]

jobs:
  init-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Display github workspace after
        run: |
          ls -a
          ls -a ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}/backup
          ls -a ${{ github.workspace }}
      - name: Upload backup
        uses: actions/upload-artifact@v3
        with:
          name: backup
          path: ${{ github.workspace }}/backup

  deploy:
    runs-on: ubuntu-latest
    needs: init-backup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download backup
        uses: actions/download-artifact@v3
        with:
          name: backup
          path: ${{ github.workspace }}
      - name: Simulate deployment
        run: |
          echo "Deploying to production"
          ls -a ${{ github.workspace }}