name: Reusable Workflow
on:
  workflow_call:
    outputs:
      date: 
        description: "Date Value"
        value: ${{ jobs.generate-output.outputs.date }}

jobs:
  nested-workflow-call:
    uses: Gh-Actions-tests/workflows/.github/workflows/reusable.yaml@main
    with:
      name: 'Nested Workflow Test'
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  generate-output:
    runs-on: ubuntu-latest
    outputs:
        date: ${{ steps.date-step.outputs.date }}
    steps:
      - id: date-step
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
