name: Calling Test Reusable Workflows
on:
  workflow_dispatch:
permissions:
  contents: read
    
jobs:
  calling-a-reusable-wf:
    uses: Gh-Actions-tests/workflows/.github/workflows/simple-reusable-workflow.yaml@main