name: Variables and Secrets
on: [push]

jobs:
  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    environment: "staging"
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: ${{ env.BOOLEAN_SECRET == 'true' }}
        run: echo "I ran"
      - name: Log vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "BOOLEAN_SECRET: $BOOLEAN_SECRET"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
  decrypt-gpg-file:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/secret.json ./resources/secret.json.gpg
      - name: View Encrypted File Content (NEVER DO THIS IRL)
        run: cat $HOME/secrets/secret.json